### ISSUE TITLE
🪲[Bug]: Error installing the RobotoMono font

### ISSUE THREAD

**Issue by GabrielFrigo4** [PSModule/Fonts#13]
### Describe the bug

When I try to install the font, everything happens as it should, the file goes to the right folder and the variable is created in the records. The problem is that the name of this variable is " (TrueType)". And this ends up making the font unusable and when I install another font (like RobotoMono-Italic) the same thing will happen, replacing the variable in the records...

Google Fonts Link: https://fonts.google.com/specimen/Roboto+Mono?query=Robot
GitHub Goole Fonts Link: https://github.com/google/fonts/tree/main/apache/robotomono

### Version information

Fonts 1.0.1

### To reproduce

# Run these commands:
`wget "https://github.com/google/fonts/raw/main/apache/robotomono/RobotoMono%5Bwght%5D.ttf" -O "RobotoMono.ttf"`
`Install-Font -Path ".\RobotoMono.ttf" -v`

### Code snippet

```powershell
REM ################################
REM Installing Roboto Mono
REM ################################

REM https://github.com/google/fonts/tree/main/apache/robotomono
wget "https://github.com/google/fonts/raw/main/apache/robotomono/RobotoMono%5Bwght%5D.ttf" -O "RobotoMono.ttf"
pwsh -c Install-Font -Path ".\RobotoMono.ttf"
del "RobotoMono.ttf"
```

### Relevant output

```Shell
VERBOSE: [Install-Font]
VERBOSE: [Install-Font] - Processing [1] scopes(s)
VERBOSE: [Install-Font] - [CurrentUser] - Processing [1] path(s)
VERBOSE: [Install-Font] - [CurrentUser] - [.\RobotoMono.ttf] - Processing
VERBOSE: [Install-Font] - [CurrentUser] - [.\RobotoMono.ttf] - File found
VERBOSE: [Install-Font] - [CurrentUser] - [C:\Users\gabri\RobotoMono.ttf] - Processing
VERBOSE: [Install-Font] - [CurrentUser] - [C:\Users\gabri\RobotoMono.ttf] - Installing font
VERBOSE: [Install-Font] - [CurrentUser] - [C:\Users\gabri\RobotoMono.ttf] - Registering font as [ (TrueType)]
VERBOSE: [Install-Font] - [CurrentUser] - [C:\Users\gabri\RobotoMono.ttf] - Done
VERBOSE: [Install-Font] - [CurrentUser] - [.\RobotoMono.ttf] - Done
VERBOSE: [Install-Font] - [CurrentUser] - Done
VERBOSE: [Install-Font] - Done
```

**Comment by MariusStorhaug** [comment]
@GabrielFrigo4, thank you for registering the bug. Will have a look at it. Also starting a new repo and module for [GoogleFonts](https://psmodule.io/GoogleFonts).

**Comment by MariusStorhaug** [comment]
I seem to get the expected behavior on my end. Could you share info from your `$PSVersionTable`?

**Comment by MariusStorhaug** [comment]
@GabrielFrigo4 ; I seem to get the expected behavior on my end. Could you share info from your `$PSVersionTable`?

**Comment by MariusStorhaug** [comment]
@GabrielFrigo4 ; You could also install the [NerdFonts](https://psmodule.io/NerdFonts) PowerShell Module and run `Install-NerdFont -Name RobotoMono`, this includes glyphs as well. For more info go to the official [NerdFonts](https://www.nerdfonts.com/) web page.

**Comment by GabrielFrigo4** [comment]
> $PSVersionTable

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by GabrielFrigo4** [comment]
> @GabrielFrigo4 ; You could also install the [NerdFonts](https://psmodule.io/NerdFonts) PowerShell Module and run `Install-NerdFont -Name RobotoMono`, this includes glyphs as well. For more info go to the official [NerdFonts](https://www.nerdfonts.com/) web page.

This command actually installed the font. But its name is slightly different than the Google font, which made me reconfigure some applications (but I found it more practical to use NerdFont than what I was doing).

I find it interesting to fix this bug, since it will probably not only occur with the RobotoMono font...

**Comment by MariusStorhaug** [comment]
@GabrielFrigo4: Can you try the latest version and see if that works? For me it works even with special characters. It will no longer use a COM object to get the font name, instead it will use the file name and just register it with the file name as its name. Also using [System.IO.FileInfo]::CopyTo(). Hopefully this also helps with another thing I want to get done: Supporting Linux and MacOS.

**Comment by GabrielFrigo4** [comment]
> @GabrielFrigo4: Can you try the latest version and see if that works after #14. For me it works even with special characters. It will no longer use a COM object to get the font name, instead it will use the file name and just register it with the file name as its name. Also using [System.IO.FileInfo]::CopyTo(). Hopefully this also helps with another thing I want to get done: Supporting Linux and MacOS.

Ok, I'll test tomorrow, today I can't use my computer

**Comment by GabrielFrigo4** [comment]
> @GabrielFrigo4: Can you try the latest version and see if that works after #14. For me it works even with special characters. It will no longer use a COM object to get the font name, instead it will use the file name and just register it with the file name as its name. Also using [System.IO.FileInfo]::CopyTo(). Hopefully this also helps with another thing I want to get done: Supporting Linux and MacOS.

Worked perfectly :)
